apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowhite-frontend
  namespace: snowhite
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: registry.ryuuga.duckdns.org/snowhite/frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: snowhite-frontend-service
  namespace: snowhite
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
