name: Dev CI/CD

on:
  push:
    branches: [ "develop" ]

jobs:
  dev-deployment:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        run: for i in {1..5}; do echo "${{ secrets.GITLAB_PASSWORD }}" | docker login registry.ryuuga.duckdns.org -u "${{ secrets.GITLAB_USERNAME }}" --password-stdin && break || sleep 2; done

      - name: Build Docker Image
        run: docker build --platform linux/arm64 -t snowhite/frontend:latest .

      - name: Tag Docker Image
        run: docker image tag snowhite/frontend:latest registry.ryuuga.duckdns.org/snowhite/frontend:latest

      - name: Push Docker Image
        run: docker push registry.ryuuga.duckdns.org/snowhite/frontend:latest
